### ISSUE TITLE
（KoikatuSunshine）This mod cause a stuck when talk with guide

### ISSUE THREAD

**Issue by AgentAsher** [ManlyMarco/KK_BecomeTrap#3]
Game UI disappear when a trap character talk with guide.Keyboard shortcut become unavailable expect ESC/F1/F2.No crash log because game still running.

**Comment by AgentAsher** [comment]
ADV UI should appear after a loading screen,in this case game won't reload.

**Comment by ManlyMarco** [comment]
Post your output_log.txt

**Comment by Rentilazer** [comment]
I have the same problem. Here is my log file.
[Player.log](https://github.com/ManlyMarco/IllusionTrapMods/files/8101693/Player.log)

**Comment by ManlyMarco** [comment]
Fixed in 78e222d5fc66566607d783fc9442d606295278ba
