### ISSUE TITLE
Mod not functioning

### ISSUE THREAD

**Issue by DarkMagicDez** [ManlyMarco/KK_BecomeTrap#4]
So i installed the one for Koikatsu Party. i have all the prerequisites properly installed but this mod seems to not function as the option never shows up in the character create menu. It's like nothing was installed. I followed the instructions as written to the letter. I don't know what else to do

**Comment by ManlyMarco** [comment]
Post your game log file, you can click log button in the config manager or runtime editor window. If you have HF patch the log is in the game root.

**Comment by DarkMagicDez** [comment]
> 

Can you use layman terms i have no idea what any of that means

**Comment by DarkMagicDez** [comment]
Is it the text file that says output log?

**Comment by DarkMagicDez** [comment]
[output_log.txt](https://github.com/ManlyMarco/IllusionTrapMods/files/9017790/output_log.txt)
i assume this is what you meant

**Comment by ManlyMarco** [comment]
Looks like you have multiple copies of this plugin meant for different games installed. Remove all of them and install only the Koikatsu version (KK).

**Comment by DarkMagicDez** [comment]
I didnt even realize i did that. hat seems to have fixed it. Thank you so much
